### ISSUE TITLE
Invalid brew tap

### ISSUE THREAD

**Issue by fahadbinrahat** [OpenSLO/homebrew-OpenSLO#1]
**Homebrew 3.4.11**

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/openslo/homebrew-openslo/Formula/oslo.rb
oslo: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the openslo/openslo tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/openslo/homebrew-openslo/Formula/oslo.rb:10

Error: Cannot tap openslo/openslo: invalid syntax in tap!

**Comment by mattupstate** [comment]
Also w/ Homebrew 3.5.1

```
$ brew tap openslo/openslo
==> Tapping openslo/openslo
Cloning into '/opt/homebrew/Library/Taps/openslo/homebrew-openslo'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 16 (delta 2), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (16/16), 6.51 KiB | 6.51 MiB/s, done.
Resolving deltas: 100% (2/2), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/openslo/homebrew-openslo/Formula/oslo.rb
oslo: wrong number of arguments (given 1, expected 0)
Error: Cannot tap openslo/openslo: invalid syntax in tap!
```

**Comment by ian-bartholomew** [comment]
Taking a look at this

**Comment by ian-bartholomew** [comment]
Updated the formula, and validated that it works on my end.  @fahadbinrahat @mattupstate can you both confirm on your ends that its working for you now? Thanks!

**Comment by mattupstate** [comment]
@ian-bartholomew yep! all good here now
<img width="989" alt="image" src="https://user-images.githubusercontent.com/166176/183785376-8ca9a4a9-3b0f-4f1e-aa1e-3b15a061283e.png">
